### register department
POST http://localhost:8080/department/register
Content-Type: application/json

{
    "username": "minhtuandepartment2",
    "password": "abc"
} 
### login department
POST http://localhost:8080/department/login
Content-Type: application/json

{
    "username":"minhtuandepartment2",
    "password": "abc"
}
