GET http://localhost:8080/
###
GET http://localhost:8080/get
###
GET http://localhost:8080/auth/login
###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "shinichiok2614",
    "password": "test"
} 
### missing pass
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "test2",
    "password": "sdfasf"
} 
### 
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "shinichiok2614",
    "password":"sdfasdf"
} 
###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "John1",
    "password":"sdfasdf"
}
###
POST http://localhost:8080/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjIsImlhdCI6MTY5MjAyMjgxNn0.6AUMXTA5ZLWjHyM1hfuZHTYY_x6QO7cTrcISbsPOQ40

###